Bibiki/Bibiki/Models/Brand.cs
using System.ComponentModel.DataAnnotations;

namespace Bibiki.Models
{
    public class Brand
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        public bool IsActive { get; set; }

    }
}

Bibiki/Bibiki/Models/ErrorViewModel.cs
namespace Bibiki.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bibiki/Bibiki/Models/Model.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bibiki.Models
{
    public class Model
    {
        [Key]
        public int Id { get; set; }
        [Required]

        [ForeignKey("Brand")]
        public int? BrandId { get; set; }
        public string? Name { get; set; }
        public bool IsActive { get; set; }

        public virtual Brand? Brand { get; set; }

    }
}

Bibiki/Bibiki/Controllers/BrandController.cs
using Bibiki.Data;
using Bibiki.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bibiki.Controllers
{
    public class BrandController : Controller
    {
        private readonly ApplicationDbContext _db;

        public BrandController(ApplicationDbContext db)
        {
            _db = db;
            
        }
        public IActionResult Index()
        {
            IEnumerable<Brand> objBrandList = _db.Brands;
            return View(objBrandList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Brand obj)
        {
            if (ModelState.IsValid) 
            {
                _db.Brands.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0) 
            { 
                return NotFound();
            }
            var brandFromDb = _db.Brands.Find(id);

            if (brandFromDb == null) 
            {
                return NotFound();
            }
            return View(brandFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Brand obj)
        {
            if (ModelState.IsValid)
            {
                _db.Brands.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

Bibiki/Bibiki/Controllers/HomeController.cs
using Bibiki.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bibiki.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bibiki/Bibiki/Controllers/ModelController.cs
using Bibiki.Data;
using Bibiki.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Bibiki.Controllers
{
    public class ModelController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ModelController(ApplicationDbContext db)
        {
            _db = db;

        }
        public IActionResult Index(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            IEnumerable<Model> objModelList = from s in  _db.Models.Include(m => m.Brand) select s;
            
            switch (sortOrder)
            {
                case "name_desc":
                    objModelList = objModelList.OrderByDescending(s => s.Name);
                    break;
                default:
                    objModelList = objModelList.OrderBy(s => s.Name);
                    break;
            }
            return View(objModelList.ToList());
        }

        public IActionResult Create()
        {
            ViewBag.Brand = new SelectList(_db.Brands, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Model obj)
        {
            if (ModelState.IsValid) 
            {
                _db.Models.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            ViewBag.Brand = new SelectList(_db.Brands, "Id", "Name");
            if (id == null || id == 0) 
            { 
                return NotFound();
            }
            var modelFromDb = _db.Models.Find(id);

            if (modelFromDb == null) 
            {
                return NotFound();
            }
            return View(modelFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Model obj)
        {
            if (ModelState.IsValid)
            {
                _db.Models.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

       
    }
}

Bibiki/Bibiki/Views/Brand/Create.cshtml
@model Brand

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-light">Добавить Производителя</h2>
            <hr />
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Добавить</button>
    <a asp-controller="Brand" asp-action="Index" class ="btn btn-dark">Назад</a>
</form>

Bibiki/Bibiki/Views/Brand/Edit.cshtml
@model Brand

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-light">Редактировать Производителя</h2>
            <hr />
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="IsActive"></label>
        <input asp-for="IsActive" class="form-check" />
    </div>
    <button type="submit" class="btn btn-primary">Обновить</button>
    <a asp-controller="Brand" asp-action="Index" class ="btn btn-dark">Назад</a>
</form>

Bibiki/Bibiki/Views/Brand/Index.cshtml
@model IEnumerable<Brand>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-light">Список производителей</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Brand" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> &nbsp; Добавить производителя
            </a>
        </div>
    </div>
</div>
<br />


<table class="table table-hover" style="width:100%">
    <thead>
        <tr class="table-dark">
            <th>
                Производитель
            </th>
        </tr>
       
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            @if (obj.IsActive == false)
            {
                <tr class="table-active">
                    <td width="50%">
                        @obj.Name
                    </td>
                    <td>
                        <div class ="w-25 btn-group" role="group">
                            <a asp-controller="Brand" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary"><i class="bi bi-pencil"></i> Изменить</a>
                        </div>
                    </td>
                </tr>
            }
            @if (obj.IsActive == true)
            {
                <tr class="table-dark">
                    <td width="50%">
                        @obj.Name
                    </td>
                    <td>
                        <div class="w-25 btn-group" role="group">
                            <a asp-controller="Brand" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary"><i class="bi bi-pencil"></i> Изменить</a>
                        </div>
                    </td>
                </tr>
            }

        }
    </tbody>

</table>

Bibiki/Bibiki/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="text-light">Welcome</h1>
    <p class="text-light">To my testovoe zadanie</p>
</div>

Bibiki/Bibiki/Views/Model/Create.cshtml
@model Model

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-light">Добавить Модель</h2>
            <hr />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="BrandId" class="control-label"></label>
        <select asp-for="BrandId" class="form-control" asp-items="ViewBag.Brand"></select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Добавить</button>
    <a asp-controller="Model" asp-action="Index" class ="btn btn-dark">Назад</a>
</form>

Bibiki/Bibiki/Views/Model/Edit.cshtml
@model Model

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-light">Редактировать Модель</h2>
            <hr />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="BrandId" class="control-label"></label>
        <select asp-for="BrandId" class="form-control" asp-items="ViewBag.Brand"></select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="IsActive"></label>
        <input asp-for="IsActive" class="form-check" />
    </div>
    <button type="submit" class="btn btn-primary">Обновить</button>
    <a asp-controller="Model" asp-action="Index" class ="btn btn-dark">Назад</a>
</form>

Bibiki/Bibiki/Views/Model/Index.cshtml
@model IEnumerable<Model>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-light">Список моделей</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Model" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> &nbsp; Добавить модель
            </a>
        </div>
    </div>
</div>
<br />


<table class="table table-hover" style="width:100%">
    <thead>
        <tr class="table-dark">
            <th>
                @Html.ActionLink("Сгрупировать", "Index", new { sortOrder = ViewBag.NameSortParm })
            </th>
            <th>
                Модель
            </th>
        </tr>
       
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            
            @if (obj.IsActive == false)
                {
                    <tr class="table-active">
                        <td width="50%">
                            @obj.Brand.Name
                        </td>
                        <td width="50%">
                            @obj.Name
                        </td>
                        <td>
                            <div class ="w-25 btn-group" role="group">
                                <a asp-controller="Model" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary"><i class="bi bi-pencil"></i> Изменить</a>
                            </div>
                        </td>
                    </tr>
                }
            @if (obj.IsActive == true)
            {
                <tr class="table-dark">
                    <td width="50%">
                        @obj.Brand.Name
                    </td>
                    <td width="50%">
                        @obj.Name
                    </td>
                    <td>
                        <div class="w-25 btn-group" role="group">
                            <a asp-controller="Model" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary"><i class="bi bi-pencil"></i> Изменить</a>
                        </div>
                    </td>
                </tr>
            }

        }
    </tbody>

</table>

Bibiki/Bibiki/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bibiki</title>
    <link rel="stylesheet" href="~/css/bootsWatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bibiki.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Bibiki</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Brand" asp-action="Index">Brand</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Model" asp-action="Index">Models</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>